name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libpq-dev gcc

      - name: Install Flet Build Tool
        run: pip install flet

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Create Android Directories
        run: mkdir -p android/app

      - name: Create Keystore File
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Use Mobile Requirements
        run: cp requirements_apk.txt requirements.txt
      # -----------------------------------------------------------------

      - name: Build APK
        env:
          FLUTTER_BUILD_STORE_FILE: android/app/upload-keystore.jks
          FLUTTER_BUILD_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          FLUTTER_BUILD_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          FLUTTER_BUILD_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          flet build apk --module-name run

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: football_league_apk
          path: build/apk/tercasfc.apk